#!/usr/bin/env python
import numpy as num
from e2rh import e2rh
from e2mr import e2mr
from e2dp import e2dp
from rh2mr import rh2mr
from rh2dp import rh2dp
from rh2e import rh2e
from mr2dp import mr2dp
from mr2e import mr2e
from mr2rh import mr2rh
from dp2e import dp2e
from dp2rh import dp2rh
from dp2mr import dp2mr

p = num.array((1000.0,))
t = num.array((260.0,))
e = num.array((1.0,))
print(p[0])
print(t[0])
print(e[0])
Tconvert = 273.15
rh = e2rh(p,t,e,Tconvert)
print(rh[0][0])
mr = e2mr(p,e)
print(mr[0])
dp = e2dp(e,t,Tconvert)
print(dp[0])
mr = rh2mr(p,t,rh[0],Tconvert)
print(mr[0][0])
dp = rh2dp(p,t,rh[0],Tconvert)
print(dp[0][0])
e  = rh2e(p,t,rh[0],Tconvert)
print(e[0][0])
dp = mr2dp(p,t,mr[0],Tconvert)
print(dp[0])
e  = mr2e(p,mr[0])
print(e[0])
rh = mr2rh(p,t,mr[0],Tconvert)
print(rh[0][0])
e  = dp2e(t,dp,Tconvert)
print(e[0])
rh = dp2rh(p,t,dp,Tconvert)
print(rh[0][0])
mr = dp2mr(p,t,dp,Tconvert)
print(mr[0])

print('OK')

p = num.array((1000.0,))
t = num.array((260.0,))
rh = num.array((50.0,))
print(p[0])
print(t[0])
print(rh[0])
Tconvert = 273.15
e  = rh2e(p,t,rh,Tconvert)
print(e[0][0])
mr = rh2mr(p,t,rh,Tconvert)
print(mr[0][0])
dp = rh2dp(p,t,rh,Tconvert)
print(dp[0][0])
rh = e2rh(p,t,e[0],Tconvert)
print(rh[0][0])
mr = e2mr(p,e[0])
print(mr[0])
dp = e2dp(e[0],t,Tconvert)
print(dp[0])
dp = mr2dp(p,t,mr[0],Tconvert)
print(dp[0])
e  = mr2e(p,mr[0])
print(e[0])
rh = mr2rh(p,t,mr[0],Tconvert)
print(rh[0][0])
e  = dp2e(t,dp,Tconvert)
print(e[0])
rh = dp2rh(p,t,dp,Tconvert)
print(rh[0][0])
mr = dp2mr(p,t,dp,Tconvert)
print(mr[0])

print('OK')

p = num.array((1000.0,))
t = num.array((260.0,))
mr = num.array((1.0,))
print(p[0])
print(t[0])
print(mr[0])
Tconvert = 273.15
dp = mr2dp(p,t,mr,Tconvert)
print(dp[0])
e  = mr2e(p,mr)
print(e[0])
rh = mr2rh(p,t,mr,Tconvert)
print(rh[0][0])
e  = rh2e(p,t,rh[0],Tconvert)
print(e[0][0])
mr = rh2mr(p,t,rh[0],Tconvert)
print(mr[0][0])
dp = rh2dp(p,t,rh[0],Tconvert)
print(dp[0][0])
rh = e2rh(p,t,e[0],Tconvert)
print(rh[0][0])
mr = e2mr(p,e[0])
print(mr[0])
dp = e2dp(e[0],t,Tconvert)
print(dp[0])
e  = dp2e(t,dp,Tconvert)
print(e[0])
rh = dp2rh(p,t,dp,Tconvert)
print(rh[0][0])
mr = dp2mr(p,t,dp,Tconvert)
print(mr[0])

print('OK')

p = num.array((1000.0,))
t = num.array((260.0,))
dp = num.array((255.0,))
print(p[0])
print(t[0])
print(dp[0])
Tconvert = 273.15
e  = dp2e(t,dp,Tconvert)
print(e[0])
rh = dp2rh(p,t,dp,Tconvert)
print(rh[0][0])
mr = dp2mr(p,t,dp,Tconvert)
print(mr[0])
dp = mr2dp(p,t,mr[0],Tconvert)
print(dp[0])
e  = mr2e(p,mr[0])
print(e[0])
rh = mr2rh(p,t,mr[0],Tconvert)
print(rh[0][0])
e  = rh2e(p,t,rh[0],Tconvert)
print(e[0][0])
mr = rh2mr(p,t,rh[0],Tconvert)
print(mr[0][0])
dp = rh2dp(p,t,rh[0],Tconvert)
print(dp[0][0])
rh = e2rh(p,t,e[0],Tconvert)
print(rh[0][0])
mr = e2mr(p,e[0])
print(mr[0])
dp = e2dp(e[0],t,Tconvert)
print(dp[0])
